config/routes.rb
BenHarrisCreative::Application.routes.draw do

  resources :contact, :only => [:index, :create], :controller => 'contact'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions, :only => :create
  resources :videos, :only => :index

  root :to => 'home#index'
  match 'blog' => 'blogs#index'
  match 'clients' => 'home#clients'

  resources :blogs, :only => :show, :as => 'blog_show'

  namespace :admin do
    resource :users, :only => [:edit, :update]
    resources :blogs
    resources :videos do
      get :refresh, :on => :member
      get :update_videos, :on => :collection
      put :update_all, :on => :collection
    end
    root :to => 'admin#index'
  end

  resources :videos, :path => '/', :only => :show
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blog = Blog.last
    @main_video = Video.main.first
    @featured_videos = Video.featured
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/blog.html.haml
.container
  .sectionTitle
    blog
.spacer
.container
  .blog
    Blog Coming Soon!

app/views/home/index.html.haml
.mainVideo
  .container
    = link_to image_tag(@main_video.thumbnail_url, width: 960, height: 539), @main_video.player_url, class: 'fancybox', 'data-width' => @main_video.width, 'data-height' => @main_video.height, 'data-title' => @main_video.title
    .videoTitle= @main_video.title
.spacer
.sectionTitle
  .container featuredWORK
.recentVideos
  .container
    - @featured_videos.each do |video|
      .left
        = link_to image_tag(video.thumbnail_url, width: 470, height: 262), video.player_url, class: 'fancybox', 'data-width' => video.width, 'data-height' => video.height, 'data-title' => video.title
        .videoTitle= video.title
.spacer
.statement
  .container
    %p
      I AM IN THE BUSINESS OF BLOWING MINDS...
      %br
      AND BUSINESS IS GOOD
    %span.viewWork= link_to 'viewVIDEOS', videos_path
.spacer
.sectionTitle
  .container recentBLOGS
.recentBlog
  .container
    - if @blog
      .blogTitle= @blog.title
      .createdAt= @blog.created_at.strftime('%B %-d, %Y')
      = simple_format truncate(@blog.body, length: 600)
      .clear
      %p
        %span.readMore= link_to 'readMore', blog_show_path(@blog)
    - else
      .blogTitle No Recent Blogs
.spacer
.sectionTitle
  .container clients
.clients
  .container
    .client.left= image_tag 'huhot_logo.png'
    .client.left= image_tag 'Marriott.png'
    .client.left= image_tag 'fizik.png'
    .client.left= image_tag 'you_can_play.png'
    .clear
    .other otherCLIENTS
    %li.client Science Matters
    %li.client City of Denver
    %li.client The Center