config/routes.rb
BenHarrisCreative::Application.routes.draw do

  resources :contact, :only => [:index, :create], :controller => 'contact'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions, :only => :create
  resources :videos, :only => :index

  root :to => 'home#index'
  match 'blog' => 'blogs#index'
  match 'clients' => 'home#clients'

  resources :blogs, :only => :show, :as => 'blog_show'

  namespace :admin do
    resource :users, :only => [:edit, :update]
    resources :blogs
    resources :videos do
      get :refresh, :on => :member
      get :update_videos, :on => :collection
      put :update_all, :on => :collection
    end
    root :to => 'admin#index'
  end

  resources :videos, :path => '/', :only => :show
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :title, :body, :created_at

  def blog_name
    title.downcase.split(' ').join('-')
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::AdminController
  before_filter :get_referer, :only => [:edit]

  def index
    @blogs = Blog.order(:created_at).all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(params[:blog])

    if @blog.save
      redirect_to admin_blogs_path
    else
      render :new
    end
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update_attributes(params[:blog])
      flash[:success] = 'You have successfully updated the blog'
      redirect_to session[:return_to]
    else
      flash[:error] = @blog.errors.full_messages.join('<br/>')
      render :edit
    end
  end

  # def destroy
  #   @blog = Blog.find(params[:id])
  #   @blog.destroy

  #   redirect_to blogs_url
  # end

  private

    def get_referer
      session[:return_to] = request.referer
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.order(:created_at).all
  end

  def show
    @blog = Blog.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/admin/blogs/_blog.html.haml
.blog
  .blogTitle= link_to blog.title, admin_blog_path(blog)
  .createdAt= blog.created_at.strftime('%B %-d, %Y')
  .blogBody= simple_format truncate(blog.body, :length => 500)
  .clear
  = link_to 'Edit Blog', edit_admin_blog_path(blog), class: 'btn btn-primary btn-large'
  .clear

app/views/admin/blogs/_form.html.haml
= form_for [:admin, @blog] do |f|
  = render 'layouts/flash', flash: flash
  .input
    %label Title
    = f.text_field :title, class: 'title'
  .input
    %label Body
    = f.text_area :body
  .submit
    = f.submit "#{submit_text} Blog", class: 'btn btn-primary btn-large'

app/views/admin/blogs/edit.html.haml
- content_for :title do
  = "Editing #{@blog.title}"

.formContainer.largeForm
  .formHeader Editing Blog
  = render 'form'

app/views/admin/blogs/index.html.haml
- content_for :title do
  Blog

= render 'layouts/flash', flash: flash
= link_to 'Create a New Blog', new_admin_blog_path, class: 'btn btn-primary btn-large'

.blogList
  = render @blogs

app/views/admin/blogs/new.html.haml
- content_for :title do
  New Blog

.formContainer.largeForm
  .formHeader Create a New Blog Entry
  = render 'form'

app/views/admin/blogs/show.html.haml
- content_for :title do
  = @blog.title

= link_to 'Back to blogs', admin_blogs_path, class: 'btn btn-primary btn-large'
.blog.noBorder
  .blogTitle= @blog.title
  .createdAt= @blog.created_at.strftime('%B %-d, %Y')
  .blogBody= @blog.body.html_safe
  = link_to 'Edit Blog', edit_admin_blog_path(@blog), class: 'btn btn-primary btn-large'
  .clear