config/routes.rb
BenHarrisCreative::Application.routes.draw do

  resources :contact, :only => [:index, :create], :controller => 'contact'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions, :only => :create
  resources :videos, :only => :index

  root :to => 'home#index'
  match 'blog' => 'blogs#index'
  match 'clients' => 'home#clients'

  resources :blogs, :only => :show, :as => 'blog_show'

  namespace :admin do
    resource :users, :only => [:edit, :update]
    resources :blogs
    resources :videos do
      get :refresh, :on => :member
      get :update_videos, :on => :collection
      put :update_all, :on => :collection
    end
    root :to => 'admin#index'
  end

  resources :videos, :path => '/', :only => :show
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :display_flag, :featured_flag, :main_flag, :user_video_url

  validates_uniqueness_of :vimeo_url, message: 'has already been used'

  def self.main
    where(main_flag: true)
  end

  def self.featured
    where(featured_flag: true)
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::AdminController
  require 'cgi'

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    vimeo_url = params[:vimeo_url]
    video_info = Vimeo.get_video_info(vimeo_url, width: 960)
    @video = Video.new

    case video_info.code
    when 404
      flash[:error] = "Sorry. That video cannot be found"
      render :new
    when 500...600
      flash[:error] = "Sorry. Something went wrong while trying to grab the video info. Please try again."
      render :new
    when 200
      @video.vimeo_id = video_info['video_id']
      @video.title = video_info['title']
      @video.description = video_info['description']
      @video.vimeo_url = vimeo_url
      @video.user_video_url = params[:user_video_url]
      @video.thumbnail_url = video_info['thumbnail_url']
      @video.embed_code = video_info['html']
      @video.player_url = extract_player_url(video_info['html'])
      @video.duration = video_info['duration']
      @video.width = video_info['width']
      @video.height = video_info['height']

      if @video.save
        flash[:success] = 'Your video has been successfully saved.'
        redirect_to admin_videos_path
      else
        flash[:error] = @video.errors.full_messages.join('<br/>')
        render :new
      end
    end
  end

  def show
    @video = Video.find(params[:id])
  end

  def destroy
    @video = Video.find(params[:id])
    if @video.destroy
      flash[:success] = 'Your video has been successfully deleted.'
    else
      flash[:error] = 'There was a problem deleting your video.'
    end
    redirect_to update_videos_admin_videos_path
  end

  def update_videos
    @videos = Video.all
  end

  def update_all
    Video.update_all(main_flag: false)
    Video.update(params[:videos].keys, params[:videos].values)

    flash[:success] = "Your videos have been successfully updated."
    redirect_to update_videos_admin_videos_path
  end

  def refresh
    @video = Video.find(params[:id])
    video_info = Vimeo.get_video_info(@video.vimeo_url, width: 960)

    case video_info.code
    when 500...600
      flash[:error] = "Sorry. Something went wrong while trying to grab the video info. Please try again."
    when 200
      @video.title = video_info['title']
      @video.description = video_info['description']
      @video.thumbnail_url = video_info['thumbnail_url']
      @video.embed_code = video_info['html']
      @video.player_url = extract_player_url(video_info['html'])
      @video.duration = video_info['duration']
      @video.width = video_info['width']
      @video.height = video_info['height']

      if @video.save
        flash[:success] = 'Your video has been successfully saved.'
      else
        flash[:error] = @video.errors.full_messages.join('<br/>')
      end
    end
    redirect_to admin_video_path(@video)
  end

  private

    def extract_player_url(url)
      CGI.unescapeHTML add_autoplay_param(url.scan(/(src=")(http:\/\/[a-z\/\.0-9\?=&;^\s]+)(")/).flatten.second)
    end

    def add_autoplay_param(base_url)
      "#{base_url}&" + { autoplay: true }.to_query
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.where(display_flag: true)
  end

  def show
    @video = Video.find_by_user_video_url(params[:id])

    redirect_to '/404' unless @video
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_form.html.haml
= form_for [:admin, @video] do |f|
  = render 'layouts/flash', flash: flash
  .input
    %label Vimeo URL
    = text_field_tag :vimeo_url
  .input
    %label Add a custom URL
    = check_box_tag :add_video_url, '1', false, class: 'toggleVideoInfo'
  .clear
  .videoInfo.hide
    .input
      %label.urlLabel= "http://#{request.host}/"
      = text_field_tag :user_video_url, '', disabled: true
  .submit
    = f.submit "Add Video", class: 'btn btn-primary btn-large'

app/views/admin/videos/_form_videos.html.haml
= form_tag update_all_admin_videos_path, method: :put do
  = render 'layouts/flash', flash: flash
  %table.videos
    %tr
      %td.tableHeader{width: 300}
        %span.text Video Title
      %td.tableHeader{width: 120}
        %span.text Display on site?
        %i.icon-question-sign.bootstrapTooltip{rel: 'tooltip', 'data-title' => 'Check this to display the video on the site'}
      %td.tableHeader{width: 120}
        %span.text Featured Video?
        %i.icon-question-sign.bootstrapTooltip{rel: 'tooltip', 'data-title' => 'Check this to feature the video on the main page'}
      %td.tableHeader 
        %span.text Main Video?
        %i.icon-question-sign.bootstrapTooltip{rel: 'tooltip', 'data-title' => 'Check this to make the video the main video on the homepage'}
      %td.tableHeader
        %span.text Custom URL
        %i.icon-question-sign.bootstrapTooltip{rel: 'tooltip', 'data-title' => 'The public url where this video will be displayed'}
      %td.tableHeader &nbsp;
    - @videos.each do |video|
      = fields_for 'videos[]', video do |f|
        %tr
          %td= video.title
          %td= f.check_box :display_flag
          %td= f.check_box :featured_flag
          %td= f.radio_button :main_flag, 'true', class: 'mainRadioButton'
          %td= f.text_field :user_video_url, size: 10, style: 'width:100px;'
          %td= link_to 'Delete', admin_video_path(video), method: :delete, data: { confirm: 'Are you sure you want to delete this video?' }
  .submit.marginLeft10
    = submit_tag "Update", class: 'btn btn-primary btn-large'

app/views/admin/videos/_video.html.haml
.video.left{class: "#{cycle('', '', 'last')}"}
  .videoThumbnail  
    = link_to image_tag(video.thumbnail_url, width: 306), admin_video_path(video)
  .title
    = video.title

app/views/admin/videos/index.html.haml
- content_for :title do
  Videos

= render 'layouts/flash', flash: flash
= link_to 'Add a new video', new_admin_video_path, class: 'btn btn-primary btn-large'
= link_to 'Edit videos', update_videos_admin_videos_path, class: 'btn btn-primary btn-large'

.videos
  = render @videos

app/views/admin/videos/new.html.haml
- content_for :title do
  Add a Video

= link_to 'Back to Videos', admin_videos_path, class: 'btn btn-primary btn-large marginBottom20'
= link_to 'Edit videos', update_videos_admin_videos_path, class: 'btn btn-primary btn-large marginBottom20'

.formContainer.largeForm.videoForm
  .formHeader Add a New Video
  = render 'form'

app/views/admin/videos/show.html.haml
- content_for :title do
  = @video.title

= link_to 'Back to videos', admin_videos_path, class: 'btn btn-primary btn-large'
= link_to 'Refresh info from Vimeo', refresh_admin_video_path, class: 'btn btn-primary btn-large'

.videoTitle= @video.title
.videoPlayer= raw @video.embed_code
.videoDescription= simple_format @video.description

app/views/admin/videos/update_videos.html.haml
- content_for :title do
  Editing Videos

= link_to 'Back to Videos', admin_videos_path, class: 'btn btn-primary btn-large marginBottom20'
= link_to 'Add a new video', new_admin_video_path, class: 'btn btn-primary btn-large marginBottom20'

.formContainer.largeForm
  .formHeader Edit Videos
  = render 'form_videos'