config/routes.rb
BenHarrisCreative::Application.routes.draw do

  resources :contact, :only => [:index, :create], :controller => 'contact'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions, :only => :create
  resources :videos, :only => :index

  root :to => 'home#index'
  match 'blog' => 'blogs#index'
  match 'clients' => 'home#clients'

  resources :blogs, :only => :show, :as => 'blog_show'

  namespace :admin do
    resource :users, :only => [:edit, :update]
    resources :blogs
    resources :videos do
      get :refresh, :on => :member
      get :update_videos, :on => :collection
      put :update_all, :on => :collection
    end
    root :to => 'admin#index'
  end

  resources :videos, :path => '/', :only => :show
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :title, :body, :created_at

  def blog_name
    title.downcase.split(' ').join('-')
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users

  attr_accessible :name, :description
  validates :name, :presence => true, :uniqueness => :true

  before_create :downcase_name


  def self.admin
    where(name: 'admin').first
  end

  private

    def downcase_name
      self.name = self.name.downcase.strip
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  belongs_to :role

  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :role_id

  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true, :confirmation => true, :on => :create
  validates :password, :presence => true, :confirmation => true, :on => :update, :unless => lambda { self.password.blank? }
  validates_presence_of :first_name, :last_name

  def to_s
    "#{first_name} #{last_initial}"
  end

  private

    def last_initial
      "#{last_name[0]}."
    end

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :display_flag, :featured_flag, :main_flag, :user_video_url

  validates_uniqueness_of :vimeo_url, message: 'has already been used'

  def self.main
    where(main_flag: true)
  end

  def self.featured
    where(featured_flag: true)
  end
end

app/models/vimeo.rb
class Vimeo
  require 'httparty'
  def self.get_video_info(url, options = {})
    HTTParty.get("http://vimeo.com/api/oembed.json?" + { url: url, 
                                                         width: options[:width], 
                                                         height: options[:height],
                                                         byline: false,
                                                         title: false,
                                                         portrait: false
                                                       }.to_query)
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::AdminController
  before_filter :get_referer, :only => [:edit]

  def index
    @blogs = Blog.order(:created_at).all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(params[:blog])

    if @blog.save
      redirect_to admin_blogs_path
    else
      render :new
    end
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update_attributes(params[:blog])
      flash[:success] = 'You have successfully updated the blog'
      redirect_to session[:return_to]
    else
      flash[:error] = @blog.errors.full_messages.join('<br/>')
      render :edit
    end
  end

  # def destroy
  #   @blog = Blog.find(params[:id])
  #   @blog.destroy

  #   redirect_to blogs_url
  # end

  private

    def get_referer
      session[:return_to] = request.referer
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  def edit
    @user = current_user
  end


  def update
    @user = current_user

    if @user.update_attributes(params[:user])
      flash[:success] = 'Your information was successfully updated'
      redirect_to edit_admin_users_path
    else
      flash[:error] = @user.errors.full_messages.join('<br/>')
      render :edit
    end
  end
end

app/controllers/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
  before_filter :require_login

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

    def not_authenticated
      flash[:error] = 'You must first login to see that page'
      redirect_to login_path
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.order(:created_at).all
  end

  def show
    @blog = Blog.find(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_filter :check_message, :only => :create

  def index
  end

  def create
    Notifier.contact(params[:name], params[:subject], params[:email], params[:message]).deliver
    flash[:success] = 'Email sent successfully'
    redirect_to contact_index_path
  end

  protected

    def check_message
      if params[:email].blank? || params[:name].blank?
        flash[:error] = 'Please enter all required fields'
        flash.keep
        redirect_to contact_index_path
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blog = Blog.last
    @main_video = Video.main.first
    @featured_videos = Video.featured
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'admin'
  before_filter :check_current_user, :only => :new
  
  def create
    user = login(params[:email], params[:password], false)
    if user
      redirect_back_or_to admin_root_path
    else
      flash[:error] = 'Email or password was invalid'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

  private

    def check_current_user
      redirect_to admin_root_path if current_user
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.where(display_flag: true)
  end

  def show
    @video = Video.find_by_user_video_url(params[:id])

    redirect_to '/404' unless @video
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def submit_text
    return 'Create' if params[:action].eql? 'new'
    'Update'
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/admin/index.html.haml
- content_for :title do
  Home

.centerText.largeText= "Welcome #{current_user.first_name}"

app/views/layouts/_admin_footer.html.haml
.footer
  .container
    &copy; 2012 Benjamin Harris; All Rights Reserved

app/views/layouts/_admin_header.html.haml
.header
  .container
    = link_to admin_root_path do
      .logo.left
    - if current_user   
      .navbar.pull-right
        %ul.nav
          %li.link= link_to 'Videos', admin_videos_path
          %li.link= link_to 'Blog', admin_blogs_path
          %li.dropdown
            = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do
              = current_user
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to edit_admin_users_path do
                  %i.icon-user
                  Edit User Info
              %li.divider
              %li= link_to 'Logout', logout_path
    .clear

app/views/layouts/_flash.html.haml
- unless flash.empty?
  - flash.each do |key, msg|
    %div{:class => "alert alert-#{key}"}
      %button.close{'data-dismiss' => 'alert'} &times;
      = msg

app/views/layouts/_footer.html.haml
.footer
  .container
    .contact.left
      %span.title.clear contact me
      .body
        .item= mail_to 'ben@benjaminharriscreative.com', 'ben@benjaminharriscreative.com'
        .item 970.397.9123
    .friends.left
      %span.title.clear friends
      %ul
        %li jerelMILLER (web developer)
        %li josiahMOTHERSHED (graphics designer)

    .followMe.left
      %span.title.clear follow me
      .social
        = link_to image_tag('f_logo.png'), 'http://www.facebook.com/benjamin.harris.547', target: '_blank'
        = link_to image_tag('Vimeo-Mobile-App-Icon.png'), 'http://www.vimeo.com/benjaminharris', target: '_blank'
    .clear
  .copyright &copy; 2012 Benjamin Harris; All Rights Reserved
  .clear

app/views/layouts/_header.html.haml
.bar.small
.container
  .header
    = link_to root_path do
      .logo.left
        .colorLogo
    .nav.right
      %ul.menu.right
        %li= link_to 'blog', blog_path
        %li= link_to 'video', videos_path
        %li= link_to 'contact', contact_index_path
    .clear

app/views/layouts/admin.html.haml
!!! XML
!!!
%html{ :'xml:lang' => "en", :lang => "en" }
  %head
    %title
      = "Admin - #{yield(:title)}"

    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  %body.admin
    .wrapper
      = render 'layouts/admin_header'
      .spacer
      .content
        .container
          = yield
      .push
      .clear
    = render 'layouts/admin_footer'

app/views/layouts/application.html.haml
!!! XML
!!!
%html{ :'xml:lang' => "en", :lang => "en" }
  %head
    %title
      - if content_for? :title
        = "Benjamin Harris Creative - #{yield :title}"
      - else
        Benjamin Harris Creative

    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  %body.main
    .wrapper
      = render 'layouts/header'
      .spacer
      = yield
      .push
      .clear
    = render 'layouts/footer'

app/views/notifier/contact.html.haml
%p
  Hi Ben! You have a new email from your website
%hr

%p
  = "From: #{@name} <#{@email}>"
%p
  = @message

app/views/notifier/contact.text.erb
Hi Ben! You have a new email from your website
----------------------------------------------

<%= "From: #{@name} <#{@email}>" %>

<% @message %>